// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TcwNzlPfd_v3rHqcZGZj2k_KFXV7luM',
    appId: '1:813294962273:web:fe4c4771b8d4806da80c20',
    messagingSenderId: '813294962273',
    projectId: 'whatucread',
    authDomain: 'whatucread.firebaseapp.com',
    storageBucket: 'whatucread.appspot.com',
    measurementId: 'G-0ZSNZLFQB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvYBb9W-79CNuwVwVYUvijSU0CpWOdahg',
    appId: '1:813294962273:android:43b6c1ff72c8c3bda80c20',
    messagingSenderId: '813294962273',
    projectId: 'whatucread',
    storageBucket: 'whatucread.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMrf1itWjFmw218I3lN_GZd_DsGLWYK24',
    appId: '1:813294962273:ios:a40084ece4c275aaa80c20',
    messagingSenderId: '813294962273',
    projectId: 'whatucread',
    storageBucket: 'whatucread.appspot.com',
    iosBundleId: 'com.example.whatUCread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMrf1itWjFmw218I3lN_GZd_DsGLWYK24',
    appId: '1:813294962273:ios:a40084ece4c275aaa80c20',
    messagingSenderId: '813294962273',
    projectId: 'whatucread',
    storageBucket: 'whatucread.appspot.com',
    iosBundleId: 'com.example.whatUCread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2TcwNzlPfd_v3rHqcZGZj2k_KFXV7luM',
    appId: '1:813294962273:web:698a2ffe35369d75a80c20',
    messagingSenderId: '813294962273',
    projectId: 'whatucread',
    authDomain: 'whatucread.firebaseapp.com',
    storageBucket: 'whatucread.appspot.com',
    measurementId: 'G-H163XN0TFX',
  );
}
